### PR TITLE
Fix some PEP 8 issues with `fix8` and `isort .`

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
_enricher/enricher.py_ used CRLF line endings which were converted to LF.

**Comment by stweil** [comment]
`flake8` reports 44 more violations of the PEP 8 style guide.

**Comment by shigapov** [comment]
@stweil, why did you remove `from .enricher import enrich` from __init__.py?

**Comment by stweil** [comment]
> @stweil, why did you remove `from .enricher import enrich` from **init**.py?

All changes were done automatically by `fix8`. That tool removes import statements which are not used in the same file. But you are right, that would break the code in this case, so I removed that part of the pull request now.

Maybe there is some way how to write \_\_init\_\_.py, so `fix8` does not break its code.

**Comment by stweil** [comment]
> Maybe there is some way how to write __init__.py, so `fix8` does not break its code.

Using `__all__` should help according to the documentation.

**Pull request merged**
